apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx:latest
    volumeMounts:
    - name: my-volume
      mountPath: /var/log/nginx
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
